// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRvSCd66gEDm2ChPvLghkTO-pLNube1c',
    appId: '1:20719904791:android:eacf85a0817c887ea01452',
    messagingSenderId: '20719904791',
    projectId: 'smart-reader-app-f9158',
    storageBucket: 'smart-reader-app-f9158.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdqmk5tNF6bzU1enc6EkgBRdWK6lmbkWk',
    appId: '1:20719904791:ios:29575307156e4941a01452',
    messagingSenderId: '20719904791',
    projectId: 'smart-reader-app-f9158',
    storageBucket: 'smart-reader-app-f9158.firebasestorage.app',
    androidClientId: '20719904791-g0fvv6s5nb1gp8k52picpi3ohm9gc6ic.apps.googleusercontent.com',
    iosClientId: '20719904791-5o3sn289p0fdgvrqikgktucp9uijmfs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartReader',
  );
}
